packages:
  - apps/**
  - packages/**
  - '!apps/web/.netlify'

catalog:
  '@eslint/js': 9.39.3
  '@total-typescript/ts-reset': ^0.6.1
  '@types/react': ^19.2.14
  eslint: 9.39.3
  prettier: ^3.8.1
  typescript: ^5.9.3
  typescript-eslint: ^8.56.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - protobufjs
  - sharp
