packages:
  - apps/**
  - packages/**
  - '!apps/web/.netlify'

catalog:
  eslint: '9.39.3'
  '@eslint/js': '9.39.3'
  typescript-eslint: ^8.56.0
  prettier: ^3.8.1
  typescript: ^5.9.3
  '@types/react': ^19.2.14
  '@total-typescript/ts-reset': ^0.6.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - protobufjs
  - sharp
