/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MediaRouteImport } from './routes/media'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdatesIndexRouteImport } from './routes/updates/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as UpdatesSlugRouteImport } from './routes/updates/$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as ApiGenerateMetadataRouteImport } from './routes/api/generate-metadata'
import { Route as ApiDraftRouteImport } from './routes/api/draft'
import { Route as ApiWebhooksSanityRouteImport } from './routes/api/webhooks/sanity'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesSlugRoute = UpdatesSlugRouteImport.update({
  id: '/updates/$slug',
  path: '/updates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateMetadataRoute = ApiGenerateMetadataRouteImport.update({
  id: '/api/generate-metadata',
  path: '/api/generate-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftRoute = ApiDraftRouteImport.update({
  id: '/api/draft',
  path: '/api/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksSanityRoute = ApiWebhooksSanityRouteImport.update({
  id: '/api/webhooks/sanity',
  path: '/api/webhooks/sanity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/components': typeof ComponentsRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/media': typeof MediaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/generate-metadata': typeof ApiGenerateMetadataRoute
  '/events/$slug': typeof EventsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/events': typeof EventsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/api/webhooks/sanity': typeof ApiWebhooksSanityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/components': typeof ComponentsRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/media': typeof MediaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/generate-metadata': typeof ApiGenerateMetadataRoute
  '/events/$slug': typeof EventsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/events': typeof EventsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/api/webhooks/sanity': typeof ApiWebhooksSanityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/components': typeof ComponentsRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/media': typeof MediaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/generate-metadata': typeof ApiGenerateMetadataRoute
  '/events/$slug': typeof EventsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/events/': typeof EventsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/api/webhooks/sanity': typeof ApiWebhooksSanityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amenities'
    | '/components'
    | '/donate'
    | '/get-involved'
    | '/media'
    | '/privacy-policy'
    | '/api/draft'
    | '/api/generate-metadata'
    | '/events/$slug'
    | '/projects/$slug'
    | '/updates/$slug'
    | '/events'
    | '/projects'
    | '/updates'
    | '/api/webhooks/sanity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amenities'
    | '/components'
    | '/donate'
    | '/get-involved'
    | '/media'
    | '/privacy-policy'
    | '/api/draft'
    | '/api/generate-metadata'
    | '/events/$slug'
    | '/projects/$slug'
    | '/updates/$slug'
    | '/events'
    | '/projects'
    | '/updates'
    | '/api/webhooks/sanity'
  id:
    | '__root__'
    | '/'
    | '/amenities'
    | '/components'
    | '/donate'
    | '/get-involved'
    | '/media'
    | '/privacy-policy'
    | '/api/draft'
    | '/api/generate-metadata'
    | '/events/$slug'
    | '/projects/$slug'
    | '/updates/$slug'
    | '/events/'
    | '/projects/'
    | '/updates/'
    | '/api/webhooks/sanity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmenitiesRoute: typeof AmenitiesRoute
  ComponentsRoute: typeof ComponentsRoute
  DonateRoute: typeof DonateRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  MediaRoute: typeof MediaRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ApiDraftRoute: typeof ApiDraftRoute
  ApiGenerateMetadataRoute: typeof ApiGenerateMetadataRoute
  EventsSlugRoute: typeof EventsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  UpdatesSlugRoute: typeof UpdatesSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
  ApiWebhooksSanityRoute: typeof ApiWebhooksSanityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$slug': {
      id: '/updates/$slug'
      path: '/updates/$slug'
      fullPath: '/updates/$slug'
      preLoaderRoute: typeof UpdatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-metadata': {
      id: '/api/generate-metadata'
      path: '/api/generate-metadata'
      fullPath: '/api/generate-metadata'
      preLoaderRoute: typeof ApiGenerateMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft': {
      id: '/api/draft'
      path: '/api/draft'
      fullPath: '/api/draft'
      preLoaderRoute: typeof ApiDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/sanity': {
      id: '/api/webhooks/sanity'
      path: '/api/webhooks/sanity'
      fullPath: '/api/webhooks/sanity'
      preLoaderRoute: typeof ApiWebhooksSanityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmenitiesRoute: AmenitiesRoute,
  ComponentsRoute: ComponentsRoute,
  DonateRoute: DonateRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  MediaRoute: MediaRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ApiDraftRoute: ApiDraftRoute,
  ApiGenerateMetadataRoute: ApiGenerateMetadataRoute,
  EventsSlugRoute: EventsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  UpdatesSlugRoute: UpdatesSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
  ApiWebhooksSanityRoute: ApiWebhooksSanityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
