// Re-export all Sanity types from the shared config package.
// These types are derived from generated TypeGen query result types.
// To regenerate: pnpm --filter @chimborazo/sanity-config schema:generate

export type {
	EventSlug,
	ProjectSlug,
	SanityAboutPage,
	SanityAmenitiesPage,
	SanityBoardMember,
	SanityDonatePage,
	SanityEvent,
	SanityEventDetail,
	SanityEventsPage,
	SanityGallery,
	SanityGalleryImage,
	SanityGetInvolvedPage,
	SanityHighlight,
	SanityHistoryPage,
	SanityHomePage,
	SanityImage,
	SanityMediaImage,
	SanityMediaPage,
	SanityPartner,
	SanityProject,
	SanityProjectCard,
	SanityProjectDetail,
	SanityProjectsPage,
	SanityQuote,
	SanitySectionHeader,
	SanitySiteSettings,
	SanitySurveyResultsPage,
	SanityUpdate,
	SanityUpdateCategory,
	SanityUpdateDetail,
	SanityUpdateEventReference,
	SanityUpdateProjectReference,
	SanityUpdatesPage,
	SanityVisionPillar,
	UpdateSlug,
} from "@chimborazo/sanity-config/types"
