import { defineQuery } from "groq"

export const getSiteSettingsQuery = defineQuery(`
  *[_type == "siteSettings"][0]{
    organizationName,
    alternativeName,
    description,
    parkAddress,
    parkHours,
    socialMedia,
    donationUrl,
    contactEmail,
    metaDefaults{
      siteTitle,
      ogImage{
        asset->{
          _id,
          url,
          metadata{
            dimensions,
            lqip
          }
        },
        alt
      }
    },
    getInvolvedGallery->{
      _id,
      title,
      images[]{
        image->{
          _id,
          title,
          image{
            asset->{
              _id,
              url,
              metadata{
                dimensions,
                lqip,
                palette
              }
            },
            alt,
            caption,
            hotspot,
            crop
          }
        }
      }
    },
    featuredQuote->{
      _id,
      quoteText,
      attribution,
      backgroundImage->{
        _id,
        title,
        image{
          asset->{
            _id,
            url,
            metadata{
              dimensions,
              lqip,
              palette
            }
          },
          alt,
          caption,
          hotspot,
          crop
        }
      }
    }
  }
`)
